### ISSUE TITLE
Use encoded JWT payload to authorise calls

### ISSUE THREAD

**Issue by approached** [jamesedmonston/graphql-authentication#29]
Hi @ all

Why you generate a graphQL token? After i have logged in. There are some graphQL token available.

![Screenshot 2020-12-09 at 12 59 32](https://user-images.githubusercontent.com/3439330/101627352-89c8cc00-3a1e-11eb-8db6-b9caa61a73fd.png)

The schema is already saved in the jwt token:
<img width="1243" alt="Screenshot 2020-12-09 at 13 02 13" src="https://user-images.githubusercontent.com/3439330/101627670-fba11580-3a1e-11eb-826a-5e3379811a99.png">

It's just a overhead, that you must every time to check and sync with the database. How do you check the jwt token, via signature or database?

**Comment by jamesedmonston** [comment]
@approached Before the plugin supported JWTs, it required the tokens to be created this way.

You're right, there's some optimisation that could be done to skip the database steps and use the JWT data directly. I'm removing support for non-JWT tokens in `1.4`, so I will add this to that list.

Thanks!

**Comment by jamesedmonston** [comment]
@approached after further investigation, I think it's going to be too much work to remove the use of 1st-party GraphQL tokens. I'd likely have to duplicate Craft's GraphQL controller and modify the authorisation behaviour, and I'm not sure it's worth the time commitment in order to reduce a couple of database calls.

Happy to accept a PR if you're willing to invest the time.

Cheers

**Comment by jamesedmonston** [comment]
@approached I've been working on some general optimisations for the next update, and have just implemented this! It'll no longer create Craft access tokens, and will use the JWT schema directly. (https://github.com/jamesedmonston/graphql-authentication/commit/44e9291c1400dc123072727e71ecc50bdeb6505e)
