### ISSUE TITLE
A usage question

### ISSUE THREAD

**Issue by sunscreem** [jamesedmonston/graphql-authentication#5]
Really glad to have spotted this plug in. I'm wondering if you think it will help in my use case.

I've two seperate domains/craft installs but the client is looking for the user auth to be shared between them both.

I'd considered using Laravel on one of the sites to "talk" to craft, maybe via graphql, to get this working. 

Any thoughts on if I'm barking up the wrong tree here?

**Comment by daltonrooney** [comment]
@sunscreem Have you considered using oAuth? You could implement https://github.com/thephpleague/oauth2-serve on the main site, and then https://github.com/thephpleague/oauth2-client on the secondary site. In that case, when clients log into site 2, they would be authenticated against site 1.

Both of these libraries integrate well into Yii2, so you could keep development as a Craft module rather than introducing Laravel into the mix.

**Comment by jamesedmonston** [comment]
@daltonrooney thanks a lot for jumping in on this one!

@sunscreem I think what you're looking for is a little out of scope for this plugin unfortunately! @daltonrooney's suggestion seems like it'd put you on the right track 👍🏻

**Comment by sunscreem** [comment]
Thanks both. That advice helped and its over to the client now :)
