### ISSUE TITLE
Improve restrictForbiddenFields

### ISSUE THREAD

**Issue by shennyg** [jamesedmonston/graphql-authentication#71]
Hey James! Thanks for this plugin, super useful!! 

We are running into an issue where we have generic field names and they are incorrectly triggering the "User doesn't have permission to access requested field(s)" error.

For example we have a field named `date` and when we run an `updateViewer` mutation the `StringHelper::containsAny($event->query, $privateFields)` is looking through the whole query as noted in your [TODO](https://github.com/jamesedmonston/graphql-authentication/blob/aa695ec87274c57a01a01b08efc8234c86ece657/src/services/RestrictionService.php#L225) and sees the word `date` in `updateViewer` and incorrectly throws the error.

Our workaround is to change the permissions to the `date` field but as we write out any new queries we need to ensure we aren't running into similar issues. I'd rather not be making commonly used fields query or mutable. 

Thanks for taking a look at this!

**Comment by jamesedmonston** [comment]
@shennyg Hey, would you be able to supply an example of your field permission settings, and the mutation/query you're firing? I'm struggling to replicate the issue locally but I'm sure I'm missing something obvious!

**Comment by jamesedmonston** [comment]
@shennyg I've just pushed https://github.com/jamesedmonston/graphql-authentication/commit/3694bab1853621865bc8e7ae7474c7c1ea86e6e8 which refactors this – it now recursively loops through the field field selections and arguments, and throws based off of that, rather than looking directly at the query string for any matches.

It'd be great if you could give that commit a whirl to see if it's all working as you'd expect.

Cheers!

**Comment by shennyg** [comment]
That did the trick, thanks so much for the quick fix!!!

**Comment by jamesedmonston** [comment]
@shennyg awesome! I've just released `1.11.4` with this fix.
